### ISSUE TITLE
Is Anybody using this API for a Native macOS Desktop Client?

### ISSUE THREAD

**Issue by lucamolteni** [zulip/swift-zulip-api#1]
### Type of Issue

- [x] Question
- [ ] Bug
- [ ] Feature Request

### Summary of Issue

Is Anybody using this API for a Native macOS Desktop Client?

I'd like to try that but if exists already I probably won't :)

**Comment by timabbott** [comment]
I am not aware of a native macOS desktop client effort, unless you count https://github.com/zulip/zulip-terminal :).

If you do decide to build one, we'd love it if you contributed improvements to this repository while you work on it :)
